/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 21
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_key = 2,
  sym_assignment = 3,
  sym_text = 4,
  sym_linebreak = 5,
  sym_format_code = 6,
  sym_format_specifier = 7,
  sym_input_key = 8,
  sym_symbol = 9,
  sym_inline_comment = 10,
  sym__newline = 11,
  sym_source_file = 12,
  sym_entry = 13,
  sym_value = 14,
  aux_sym_source_file_repeat1 = 15,
  aux_sym_value_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_key] = "key",
  [sym_assignment] = "assignment",
  [sym_text] = "text",
  [sym_linebreak] = "linebreak",
  [sym_format_code] = "format_code",
  [sym_format_specifier] = "format_specifier",
  [sym_input_key] = "input_key",
  [sym_symbol] = "symbol",
  [sym_inline_comment] = "inline_comment",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_entry] = "entry",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_key] = sym_key,
  [sym_assignment] = sym_assignment,
  [sym_text] = sym_text,
  [sym_linebreak] = sym_linebreak,
  [sym_format_code] = sym_format_code,
  [sym_format_specifier] = sym_format_specifier,
  [sym_input_key] = sym_input_key,
  [sym_symbol] = sym_symbol,
  [sym_inline_comment] = sym_inline_comment,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_entry] = sym_entry,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_linebreak] = {
    .visible = true,
    .named = true,
  },
  [sym_format_code] = {
    .visible = true,
    .named = true,
  },
  [sym_format_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_input_key] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assignment = 1,
  field_comment = 2,
  field_key = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assignment] = "assignment",
  [field_comment] = "comment",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
  [3] = {.index = 5, .length = 3},
  [4] = {.index = 8, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assignment, 1},
    {field_key, 0},
  [2] =
    {field_assignment, 1},
    {field_comment, 2},
    {field_key, 0},
  [5] =
    {field_assignment, 1},
    {field_key, 0},
    {field_value, 2},
  [8] =
    {field_assignment, 1},
    {field_comment, 3},
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 2,
  [6] = 3,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 11,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '\t', 5,
        '\n', 58,
        '\r', 1,
        '#', 2,
        '%', 8,
        ':', 31,
        '=', 43,
        '~', 28,
        0xa7, 35,
      );
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(40);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(51);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead == '$') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 's') ADVANCE(54);
      END_STATE();
    case 8:
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '%' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 's') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 10:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 13:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'k') ADVANCE(11);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 15:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(17);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 't') ADVANCE(10);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 17:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'u') ADVANCE(16);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == 'y') ADVANCE(9);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 20:
      if (lookahead == ':') ADVANCE(56);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      if (lookahead == ':') ADVANCE(55);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == 'A') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'B') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'I') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 'K') ADVANCE(33);
      END_STATE();
    case 28:
      if (lookahead == 'L') ADVANCE(26);
      END_STATE();
    case 29:
      if (lookahead == 'N') ADVANCE(24);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(25);
      END_STATE();
    case 31:
      if (lookahead == '_') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 32:
      if (lookahead == 'f') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      if (lookahead == '~') ADVANCE(52);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'G') ||
          ('K' <= lookahead && lookahead <= 'O') ||
          lookahead == 'R' ||
          ('a' <= lookahead && lookahead <= 'g') ||
          ('k' <= lookahead && lookahead <= 'o') ||
          lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 36:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '\t', 5,
        '\n', 58,
        '\r', 1,
        ' ', 44,
        '#', 46,
        '%', 47,
        ':', 49,
        '~', 48,
        0xa7, 50,
      );
      if (lookahead != 0) ADVANCE(45);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '\n') ADVANCE(58);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '=') ADVANCE(42);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          lookahead == '=') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '#') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_key);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_assignment);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '%' &&
          lookahead != ':' &&
          lookahead != '~' &&
          lookahead != 0xa7) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '#' &&
          lookahead != '%' &&
          lookahead != ':' &&
          lookahead != '~' &&
          lookahead != 0xa7) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '#') ADVANCE(57);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == '%' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 's') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(6);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'L') ADVANCE(26);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '_') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(19);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'G') ||
          ('K' <= lookahead && lookahead <= 'O') ||
          lookahead == 'R' ||
          ('a' <= lookahead && lookahead <= 'g') ||
          ('k' <= lookahead && lookahead <= 'o') ||
          lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_linebreak);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_format_code);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_format_specifier);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_input_key);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_symbol);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 36},
  [3] = {.lex_state = 36},
  [4] = {.lex_state = 36},
  [5] = {.lex_state = 36},
  [6] = {.lex_state = 36},
  [7] = {.lex_state = 36},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 37},
  [10] = {.lex_state = 37},
  [11] = {.lex_state = 36},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 36},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_assignment] = ACTIONS(1),
    [sym_linebreak] = ACTIONS(1),
    [sym_format_code] = ACTIONS(1),
    [sym_format_specifier] = ACTIONS(1),
    [sym_input_key] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_inline_comment] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_entry] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_value] = STATE(11),
    [aux_sym_value_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(11),
    [sym_text] = ACTIONS(13),
    [sym_linebreak] = ACTIONS(15),
    [sym_format_code] = ACTIONS(15),
    [sym_format_specifier] = ACTIONS(15),
    [sym_input_key] = ACTIONS(15),
    [sym_symbol] = ACTIONS(13),
    [sym_inline_comment] = ACTIONS(17),
    [sym__newline] = ACTIONS(11),
  },
  [STATE(3)] = {
    [aux_sym_value_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_text] = ACTIONS(21),
    [sym_linebreak] = ACTIONS(23),
    [sym_format_code] = ACTIONS(23),
    [sym_format_specifier] = ACTIONS(23),
    [sym_input_key] = ACTIONS(23),
    [sym_symbol] = ACTIONS(21),
    [sym_inline_comment] = ACTIONS(19),
    [sym__newline] = ACTIONS(19),
  },
  [STATE(4)] = {
    [aux_sym_value_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_text] = ACTIONS(27),
    [sym_linebreak] = ACTIONS(30),
    [sym_format_code] = ACTIONS(30),
    [sym_format_specifier] = ACTIONS(30),
    [sym_input_key] = ACTIONS(30),
    [sym_symbol] = ACTIONS(27),
    [sym_inline_comment] = ACTIONS(25),
    [sym__newline] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym_value] = STATE(16),
    [aux_sym_value_repeat1] = STATE(6),
    [sym_text] = ACTIONS(33),
    [sym_linebreak] = ACTIONS(35),
    [sym_format_code] = ACTIONS(35),
    [sym_format_specifier] = ACTIONS(35),
    [sym_input_key] = ACTIONS(35),
    [sym_symbol] = ACTIONS(33),
    [sym_inline_comment] = ACTIONS(17),
    [sym__newline] = ACTIONS(11),
  },
  [STATE(6)] = {
    [aux_sym_value_repeat1] = STATE(7),
    [sym_text] = ACTIONS(37),
    [sym_linebreak] = ACTIONS(39),
    [sym_format_code] = ACTIONS(39),
    [sym_format_specifier] = ACTIONS(39),
    [sym_input_key] = ACTIONS(39),
    [sym_symbol] = ACTIONS(37),
    [sym_inline_comment] = ACTIONS(19),
    [sym__newline] = ACTIONS(19),
  },
  [STATE(7)] = {
    [aux_sym_value_repeat1] = STATE(7),
    [sym_text] = ACTIONS(41),
    [sym_linebreak] = ACTIONS(44),
    [sym_format_code] = ACTIONS(44),
    [sym_format_specifier] = ACTIONS(44),
    [sym_input_key] = ACTIONS(44),
    [sym_symbol] = ACTIONS(41),
    [sym_inline_comment] = ACTIONS(25),
    [sym__newline] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(49), 1,
      sym_comment,
    ACTIONS(51), 1,
      sym__newline,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(13), 1,
      sym_entry,
  [19] = 6,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      sym_comment,
    ACTIONS(58), 1,
      sym_key,
    ACTIONS(61), 1,
      sym__newline,
    STATE(9), 1,
      aux_sym_source_file_repeat1,
    STATE(19), 1,
      sym_entry,
  [38] = 2,
    ACTIONS(64), 1,
      sym_key,
    ACTIONS(53), 3,
      ts_builtin_sym_end,
      sym_comment,
      sym__newline,
  [47] = 2,
    ACTIONS(68), 1,
      sym_inline_comment,
    ACTIONS(66), 2,
      ts_builtin_sym_end,
      sym__newline,
  [55] = 2,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 1,
      sym__newline,
  [62] = 2,
    ACTIONS(70), 1,
      sym__newline,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
  [69] = 1,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      sym__newline,
  [74] = 1,
    ACTIONS(76), 2,
      ts_builtin_sym_end,
      sym__newline,
  [79] = 2,
    ACTIONS(66), 1,
      sym__newline,
    ACTIONS(68), 1,
      sym_inline_comment,
  [86] = 1,
    ACTIONS(78), 1,
      sym_assignment,
  [90] = 1,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
  [94] = 1,
    ACTIONS(70), 1,
      sym__newline,
  [98] = 1,
    ACTIONS(82), 1,
      sym_assignment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 19,
  [SMALL_STATE(10)] = 38,
  [SMALL_STATE(11)] = 47,
  [SMALL_STATE(12)] = 55,
  [SMALL_STATE(13)] = 62,
  [SMALL_STATE(14)] = 69,
  [SMALL_STATE(15)] = 74,
  [SMALL_STATE(16)] = 79,
  [SMALL_STATE(17)] = 86,
  [SMALL_STATE(18)] = 90,
  [SMALL_STATE(19)] = 94,
  [SMALL_STATE(20)] = 98,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 2, 0, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 3, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_entry, 4, 0, 4),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [80] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
