/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 6
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_file_token1 = 1,
  anon_sym_NULL = 2,
  aux_sym__line_token1 = 3,
  sym_key = 4,
  sym_assignment = 5,
  aux_sym_value_token1 = 6,
  sym_comment = 7,
  sym_inline_comment = 8,
  sym_text = 9,
  sym_linebreak = 10,
  sym_format_code = 11,
  sym_input_key = 12,
  sym_format_specifier = 13,
  sym_emoji = 14,
  sym_source_file = 15,
  sym__line = 16,
  sym_value = 17,
  aux_sym_source_file_repeat1 = 18,
  aux_sym_value_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_file_token1] = "source_file_token1",
  [anon_sym_NULL] = "\0",
  [aux_sym__line_token1] = "_line_token1",
  [sym_key] = "key",
  [sym_assignment] = "assignment",
  [aux_sym_value_token1] = "value_token1",
  [sym_comment] = "comment",
  [sym_inline_comment] = "inline_comment",
  [sym_text] = "text",
  [sym_linebreak] = "linebreak",
  [sym_format_code] = "format_code",
  [sym_input_key] = "input_key",
  [sym_format_specifier] = "format_specifier",
  [sym_emoji] = "emoji",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_value_repeat1] = "value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_file_token1] = aux_sym_source_file_token1,
  [anon_sym_NULL] = anon_sym_NULL,
  [aux_sym__line_token1] = aux_sym__line_token1,
  [sym_key] = sym_key,
  [sym_assignment] = sym_assignment,
  [aux_sym_value_token1] = aux_sym_value_token1,
  [sym_comment] = sym_comment,
  [sym_inline_comment] = sym_inline_comment,
  [sym_text] = sym_text,
  [sym_linebreak] = sym_linebreak,
  [sym_format_code] = sym_format_code,
  [sym_input_key] = sym_input_key,
  [sym_format_specifier] = sym_format_specifier,
  [sym_emoji] = sym_emoji,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_value_repeat1] = aux_sym_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_NULL] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_linebreak] = {
    .visible = true,
    .named = true,
  },
  [sym_format_code] = {
    .visible = true,
    .named = true,
  },
  [sym_input_key] = {
    .visible = true,
    .named = true,
  },
  [sym_format_specifier] = {
    .visible = true,
    .named = true,
  },
  [sym_emoji] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_assignment = 1,
  field_key = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_assignment] = "assignment",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 3},
  [2] = {.index = 3, .length = 2},
  [3] = {.index = 5, .length = 6},
  [4] = {.index = 11, .length = 2},
  [5] = {.index = 13, .length = 3},
  [6] = {.index = 16, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_assignment, 0, .inherited = true},
    {field_key, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_assignment, 1},
    {field_key, 0},
  [5] =
    {field_assignment, 0, .inherited = true},
    {field_assignment, 1, .inherited = true},
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [11] =
    {field_assignment, 2},
    {field_key, 1},
  [13] =
    {field_assignment, 1},
    {field_key, 0},
    {field_value, 2},
  [16] =
    {field_assignment, 2},
    {field_key, 1},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if ((!eof && lookahead == 00)) ADVANCE(11);
      if (lookahead == '#') ADVANCE(4);
      if (lookahead == '=') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if ((!eof && lookahead == 00)) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(24);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(20);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 2:
      if ((!eof && lookahead == 00)) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(25);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if ((!eof && lookahead == 00)) ADVANCE(11);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(3);
      END_STATE();
    case 4:
      if (lookahead == '#') ADVANCE(23);
      END_STATE();
    case 5:
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\n' ||
          lookahead == '\r') SKIP(5);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(17);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '=') ADVANCE(17);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\t') ADVANCE(24);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(20);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(20);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\t') ADVANCE(25);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_source_file_token1);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(3);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_NULL);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_NULL);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym__line_token1);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(13);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '#') ADVANCE(15);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '=') ADVANCE(17);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '#') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '\r' ||
          lookahead == '=') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_key);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '=') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_assignment);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_value_token1);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if ((!eof && lookahead == 00)) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(24);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(20);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(20);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if ((!eof && lookahead == 00)) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(24);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(21);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_value_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_inline_comment);
      if ((!eof && lookahead == 00)) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(24);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(21);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_inline_comment);
      if ((!eof && lookahead == 00)) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(25);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_inline_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6},
  [2] = {.lex_state = 1, .external_lex_state = 2},
  [3] = {.lex_state = 1, .external_lex_state = 2},
  [4] = {.lex_state = 1, .external_lex_state = 2},
  [5] = {.lex_state = 1, .external_lex_state = 2},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_NULL] = ACTIONS(1),
    [sym_assignment] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_linebreak] = ACTIONS(1),
    [sym_format_code] = ACTIONS(1),
    [sym_input_key] = ACTIONS(1),
    [sym_format_specifier] = ACTIONS(1),
    [sym_emoji] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(21),
    [sym__line] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym__line_token1] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_value] = STATE(10),
    [aux_sym_value_repeat1] = STATE(4),
    [aux_sym_source_file_token1] = ACTIONS(11),
    [anon_sym_NULL] = ACTIONS(11),
    [aux_sym_value_token1] = ACTIONS(13),
    [sym_inline_comment] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
    [sym_linebreak] = ACTIONS(17),
    [sym_format_code] = ACTIONS(17),
    [sym_input_key] = ACTIONS(17),
    [sym_format_specifier] = ACTIONS(17),
  },
  [STATE(3)] = {
    [sym_value] = STATE(11),
    [aux_sym_value_repeat1] = STATE(4),
    [aux_sym_source_file_token1] = ACTIONS(19),
    [anon_sym_NULL] = ACTIONS(19),
    [aux_sym_value_token1] = ACTIONS(13),
    [sym_inline_comment] = ACTIONS(21),
    [sym_text] = ACTIONS(17),
    [sym_linebreak] = ACTIONS(17),
    [sym_format_code] = ACTIONS(17),
    [sym_input_key] = ACTIONS(17),
    [sym_format_specifier] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(25), 1,
      aux_sym_value_token1,
    STATE(5), 1,
      aux_sym_value_repeat1,
    ACTIONS(23), 3,
      aux_sym_source_file_token1,
      anon_sym_NULL,
      sym_inline_comment,
    ACTIONS(27), 5,
      sym_text,
      sym_linebreak,
      sym_format_code,
      sym_input_key,
      sym_format_specifier,
  [19] = 4,
    ACTIONS(31), 1,
      aux_sym_value_token1,
    STATE(5), 1,
      aux_sym_value_repeat1,
    ACTIONS(29), 3,
      aux_sym_source_file_token1,
      anon_sym_NULL,
      sym_inline_comment,
    ACTIONS(34), 5,
      sym_text,
      sym_linebreak,
      sym_format_code,
      sym_input_key,
      sym_format_specifier,
  [38] = 6,
    ACTIONS(5), 1,
      aux_sym__line_token1,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(9), 1,
      sym_comment,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(12), 1,
      sym__line,
  [57] = 6,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(41), 1,
      aux_sym__line_token1,
    ACTIONS(44), 1,
      sym_key,
    ACTIONS(47), 1,
      sym_comment,
    STATE(7), 1,
      aux_sym_source_file_repeat1,
    STATE(12), 1,
      sym__line,
  [76] = 2,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 3,
      aux_sym__line_token1,
      sym_key,
      sym_comment,
  [85] = 2,
    ACTIONS(50), 1,
      ts_builtin_sym_end,
    ACTIONS(52), 3,
      aux_sym__line_token1,
      sym_key,
      sym_comment,
  [94] = 2,
    ACTIONS(56), 1,
      sym_inline_comment,
    ACTIONS(54), 2,
      aux_sym_source_file_token1,
      anon_sym_NULL,
  [102] = 2,
    ACTIONS(60), 1,
      sym_inline_comment,
    ACTIONS(58), 2,
      aux_sym_source_file_token1,
      anon_sym_NULL,
  [110] = 2,
    ACTIONS(62), 1,
      aux_sym_source_file_token1,
    ACTIONS(64), 1,
      anon_sym_NULL,
  [117] = 2,
    ACTIONS(66), 1,
      sym_key,
    ACTIONS(68), 1,
      sym_comment,
  [124] = 2,
    ACTIONS(70), 1,
      aux_sym_source_file_token1,
    ACTIONS(72), 1,
      anon_sym_NULL,
  [131] = 2,
    ACTIONS(74), 1,
      aux_sym_source_file_token1,
    ACTIONS(76), 1,
      anon_sym_NULL,
  [138] = 2,
    ACTIONS(78), 1,
      aux_sym_source_file_token1,
    ACTIONS(80), 1,
      anon_sym_NULL,
  [145] = 2,
    ACTIONS(82), 1,
      aux_sym_source_file_token1,
    ACTIONS(84), 1,
      anon_sym_NULL,
  [152] = 2,
    ACTIONS(86), 1,
      aux_sym_source_file_token1,
    ACTIONS(88), 1,
      anon_sym_NULL,
  [159] = 1,
    ACTIONS(90), 1,
      sym_assignment,
  [163] = 1,
    ACTIONS(92), 1,
      sym_assignment,
  [167] = 1,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 19,
  [SMALL_STATE(6)] = 38,
  [SMALL_STATE(7)] = 57,
  [SMALL_STATE(8)] = 76,
  [SMALL_STATE(9)] = 85,
  [SMALL_STATE(10)] = 94,
  [SMALL_STATE(11)] = 102,
  [SMALL_STATE(12)] = 110,
  [SMALL_STATE(13)] = 117,
  [SMALL_STATE(14)] = 124,
  [SMALL_STATE(15)] = 131,
  [SMALL_STATE(16)] = 138,
  [SMALL_STATE(17)] = 145,
  [SMALL_STATE(18)] = 152,
  [SMALL_STATE(19)] = 159,
  [SMALL_STATE(20)] = 163,
  [SMALL_STATE(21)] = 167,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 2),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 4),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_value_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(13),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(19),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 3), SHIFT_REPEAT(12),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 1),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 5),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 4, 0, 6),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 3, 0, 2),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 3, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 4, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 4, 0, 4),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 4, 0, 5),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 4, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 5, 0, 6),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 5, 0, 6),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [94] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_text = 0,
  ts_external_token_linebreak = 1,
  ts_external_token_format_code = 2,
  ts_external_token_input_key = 3,
  ts_external_token_format_specifier = 4,
  ts_external_token_emoji = 5,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_text] = sym_text,
  [ts_external_token_linebreak] = sym_linebreak,
  [ts_external_token_format_code] = sym_format_code,
  [ts_external_token_input_key] = sym_input_key,
  [ts_external_token_format_specifier] = sym_format_specifier,
  [ts_external_token_emoji] = sym_emoji,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_text] = true,
    [ts_external_token_linebreak] = true,
    [ts_external_token_format_code] = true,
    [ts_external_token_input_key] = true,
    [ts_external_token_format_specifier] = true,
    [ts_external_token_emoji] = true,
  },
  [2] = {
    [ts_external_token_text] = true,
    [ts_external_token_linebreak] = true,
    [ts_external_token_format_code] = true,
    [ts_external_token_input_key] = true,
    [ts_external_token_format_specifier] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_lang_external_scanner_create(void);
void tree_sitter_lang_external_scanner_destroy(void *);
bool tree_sitter_lang_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_lang_external_scanner_serialize(void *, char *);
void tree_sitter_lang_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_lang_external_scanner_create,
      tree_sitter_lang_external_scanner_destroy,
      tree_sitter_lang_external_scanner_scan,
      tree_sitter_lang_external_scanner_serialize,
      tree_sitter_lang_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "lang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
